name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env
        run: cp srcs/.env.example srcs/.env

      - name: Build & start containers
        run: make up

      - name: Check containers are running
        run: make ps

      - name: Teardown
        if: always()
        run: make down
